[build]
builder = "nixpacks"
buildCommand = "./build.sh"

[deploy]
startCommand = "cd Portfolio && gunicorn Portfolio.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.envs]
PYTHON_VERSION = "3.11.10"
PORT = "8000"