# Generated by Django 5.1.2 on 2024-11-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0001_initial'),
    ]

    operations = [
    ]
