# Generated by Django 5.1.2 on 2024-11-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='newsletter_issue',
            field=models.IntegerField(default=1, help_text='Newsletter issue number'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='preview_content',
            field=models.TextField(blank=True, help_text='Short preview/excerpt from the LinkedIn article'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the article', upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='linkedin_url',
            field=models.URLField(help_text='URL to the LinkedIn newsletter article'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='reading_time',
            field=models.IntegerField(default=5, help_text='Estimated reading time in minutes'),
        ),
    ]
